pull_request_rules:
  - name: BB backport provenance source
    conditions:
      - merged
      - title = BB backport collision source
    actions:
      backport:
        branches:
          - release-bb
        title: "BB collision source (backport #{{ number }})"

  - name: BB trusted bot backport auto merge
    conditions:
      - author = mergify[bot]
      - base = release-bb
      - head ~= ^mergify/bp/release-bb/pr-
    actions:
      merge:
        method: merge
